export const ROUTES = {
  HOME: '/',
  PRICING: '/pricing',
  CATALOGUE: '/catalogue',
  CATALOGUE_BOOK_DETAILS: (bookId: string) => `/catalogue/books/${bookId}`,
  CATALOGUE_AUTHORS: '/catalogue/authors',
  CATALOGUE_AUTHOR_DETAILS: (authorId: string) =>
    `/catalogue/authors/${authorId}`,
  CATALOGUE_CATEGORIES: '/catalogue/categories',
  CATALOGUE_CATEGORY_DETAILS: (categoryId: string) =>
    `/catalogue/categories/${categoryId}`,
  SEARCH: '/search',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  VERIFY_EMAIL: '/auth/verify-email',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  CALLBACK: '/auth/callback',
  DASHBOARD: '/dashboard',
  DASHBOARD_LIBRARY: '/dashboard/library',
  DASHBOARD_READING_HISTORY: '/dashboard/reading/history',
  DASHBOARD_READING_CURRENTLY_READING: '/dashboard/reading/currently-reading',
  DASHBOARD_READING_COMPLETED: '/dashboard/reading/completed',
  DASHBOARD_READ_BOOK: (bookId: string) => `/dashboard/read/${bookId}`,
  DASHBOARD_READ_BOOK_BOOKMARKS: (bookId: string) =>
    `/dashboard/read/${bookId}/bookmarks`,
  DASHBOARD_READ_BOOK_HIGHLIGHTS: (bookId: string) =>
    `/dashboard/read/${bookId}/highlights`,
  DASHBOARD_WISHLIST: '/dashboard/wishlist',
  DASHBOARD_BORROWS: '/dashboard/borrows',
  DASHBOARD_RESERVATIONS: '/dashboard/reservations',
  DASHBOARD_NOTIFICATIONS: '/dashboard/notifications',
  DASHBOARD_SUBSCRIPTION: '/dashboard/subscription',
  DASHBOARD_SUBSCRIPTION_HISTORY: '/dashboard/subscription/history',
  DASHBOARD_CHECKOUT: '/dashboard/checkout',
  DASHBOARD_CHECKOUT_RESULT: '/dashboard/checkout/result',
  DASHBOARD_PAYMENTS: '/dashboard/payments',
  DASHBOARD_SETTINGS_PROFILE: '/dashboard/settings/profile',
  DASHBOARD_SETTINGS_SECURITY: '/dashboard/settings/security',
  DASHBOARD_SETTINGS_NOTIFICATIONS: '/dashboard/settings/notifications',
  DASHBOARD_ONBOARDING_PLANS: '/dashboard/onboarding/plans',
  DASHBOARD_ONBOARDING_COMPLETE: '/dashboard/onboarding/complete',
  ADMIN: '/admin',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_2FA: '/admin/2fa',
  ADMIN_BOOKS: '/admin/books',
  ADMIN_BOOKS_NEW: '/admin/books/new',
  ADMIN_BOOKS_EDIT: (bookId: string) => `/admin/books/${bookId}/edit`,
  ADMIN_BOOKS_IMPORT: '/admin/books/import',
  ADMIN_AUTHORS: '/admin/authors',
  ADMIN_AUTHOR_DETAILS: (authorId: string) => `/admin/authors/${authorId}`,
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_CATEGORY_DETAILS: (categoryId: string) =>
    `/admin/categories/${categoryId}`,
  ADMIN_MEMBERS: '/admin/members',
  ADMIN_MEMBER_DETAILS: (userId: string) => `/admin/members/${userId}`,
  ADMIN_SUBSCRIPTIONS: '/admin/subscriptions',
  ADMIN_SUBSCRIPTION_DETAILS: (id: string) => `/admin/subscriptions/${id}`,
  ADMIN_PAYMENTS: '/admin/payments',
  ADMIN_PAYMENT_DETAILS: (id: string) => `/admin/payments/${id}`,
  ADMIN_PROMOTIONS_COUPONS: '/admin/promotions/coupons',
  ADMIN_PROMOTIONS_FLASH_SALES: '/admin/promotions/flash-sales',
  ADMIN_REVIEWS: '/admin/reviews',
  ADMIN_RESERVATIONS: '/admin/reservations',
  ADMIN_BORROWS: '/admin/borrows',
  ADMIN_STAFF: '/admin/staff',
  ADMIN_STAFF_DETAILS: (staffId: string) => `/admin/staff/${staffId}`,
  ADMIN_RBAC_ROLES: '/admin/rbac/roles',
  ADMIN_RBAC_ROLE_DETAILS: (roleId: string) => `/admin/rbac/roles/${roleId}`,
  ADMIN_AUDIT: '/admin/audit',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_REPORT_DETAILS: (reportId: string) => `/admin/reports/${reportId}`,
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_NOTIFICATIONS: '/admin/notifications',
  MAINTENANCE: '/maintenance',
} as const
